package com.andremanuelbarbosa.editorgrafico;

import java.awt.*;
import javax.swing.*;

/** Classe que representa a janela de op��es
 */
public class DrawProg extends javax.swing.JFrame 
{
    DrawArea drawArea;
    static final int LINETOOL = 0;
    static final int RECTTOOL = 1;
    static final int POLYTOOL = 2;
    static final int OVALTOOL = 3;
    
    protected int toolSelected;
    private AnyTool[] tools = new AnyTool[4];
    
    private ButtonGroup buttonG;
    
    protected MyCanvas myCanvas;
    private JColorChooser jcc = new JColorChooser();
    
    boolean flag = false;
    
    /** Constructor da classe DrawProg
     */    
    public DrawProg() 
    {
        tools[LINETOOL] = new LineTool();
        tools[RECTTOOL] = new RectTool();
        tools[POLYTOOL] = new PolyTool();
        tools[OVALTOOL] = new OvalTool();
        
        toolSelected = -1;
        
        initComponents();
        
        buttonG = new ButtonGroup();
        
        buttonG.add(jToggleButton1);
        buttonG.add(jToggleButton2);
        buttonG.add(jToggleButton3);
        buttonG.add(jToggleButton4);
        
        jCheckBox1.setEnabled(false);
        
        drawArea = createDrawArea();
        jDesktopPane1.add(drawArea);
        jDesktopPane1.setPreferredSize(new Dimension(drawArea.getWidth() + 2 * drawArea.getMargin(), drawArea.getHeight() + 2 * drawArea.getMargin()));
        pack();        
    }

    private DrawArea createDrawArea()
    {
        DrawArea dArea = new DrawArea(this);
        dArea.setVisible(true);

        try 
        {
            dArea.setSelected(true);
        } 
        catch (Exception e) {};

        return(dArea);
    } 

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setTitle("Draw Program");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(120, 100));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XY");
        jLabel1.setToolTipText("Coordenadas do rato no painel");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 18));
        jPanel1.add(jLabel1);

        jTextField1.setColumns(6);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Coordenadas do rato no painel");
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        
        System.out.println(getClass().getResource("../../..").toString());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trab1/line.gif")));
        jToggleButton1.setToolTipText("Line");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(60, 26));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(60, 26));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(22, 20));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton1MousePressed(evt);
            }
        });

        jPanel1.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trab1/rect.gif")));
        jToggleButton2.setToolTipText("Rect");
        jToggleButton2.setPreferredSize(new java.awt.Dimension(22, 20));
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton2MousePressed(evt);
            }
        });

        jPanel1.add(jToggleButton2);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trab1/poly.gif")));
        jToggleButton3.setToolTipText("Poly");
        jToggleButton3.setMaximumSize(new java.awt.Dimension(60, 26));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(60, 26));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(22, 20));
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton3MousePressed(evt);
            }
        });

        jPanel1.add(jToggleButton3);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trab1/ellipse.gif")));
        jToggleButton4.setToolTipText("Oval");
        jToggleButton4.setPreferredSize(new java.awt.Dimension(22, 20));
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton4MousePressed(evt);
            }
        });

        jPanel1.add(jToggleButton4);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trab1/del.jpg")));
        jButton4.setToolTipText("Limpar");
        jButton4.setPreferredSize(new java.awt.Dimension(22, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setToolTipText("Cor");
        jButton5.setPreferredSize(new java.awt.Dimension(22, 20));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton5);

        jCheckBox1.setText("A cheio?");
        jCheckBox1.setToolTipText("Activa/Desactiva o preenchimento do fundo");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox1MousePressed(evt);
            }
        });

        jPanel1.add(jCheckBox1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        pack();
    }//GEN-END:initComponents

    private void jToggleButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MousePressed
        changeTool(OVALTOOL);
        jCheckBox1.setEnabled(true);
    }//GEN-LAST:event_jToggleButton4MousePressed

    private void jCheckBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MousePressed
        flag = !flag;
    }//GEN-LAST:event_jCheckBox1MousePressed

    private void jToggleButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MousePressed
        changeTool(POLYTOOL);
        jCheckBox1.setEnabled(true);
    }//GEN-LAST:event_jToggleButton3MousePressed

    private void jToggleButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MousePressed
        changeTool(RECTTOOL);
        jCheckBox1.setEnabled(true);
    }//GEN-LAST:event_jToggleButton2MousePressed

    private void jToggleButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MousePressed
        changeTool(LINETOOL);
        jCheckBox1.setEnabled(false);
    }//GEN-LAST:event_jToggleButton1MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (getToolSelected() != null) 
        {
            getToolSelected().resetTool();
        }
        myCanvas.clearObjectos();
        myCanvas.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Color c = jcc.showDialog(null,"Selecione a cor pretendida",myCanvas.getColor());
        
        if(c != null)
        {
            myCanvas.changeColor(c);
            jButton5.setBackground(c);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /** M�todo execut�vel
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        new DrawProg().show();
    }
    
    /** Coloca o valor das coordenadas de posi��o do rato na jtextfield
     * @param x Coordenada x
     * @param y Coordenada y
     */    
    public void setXY (int x, int y)
    {
        String aux = x + ", " + y;
        jTextField1.setText (aux);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
    
    /** Muda a ferramenta com que se est� a trabalhar
     * @param newTool Nova ferramenta
     */    
    public void changeTool (int newTool)
    {
        toolSelected = newTool;
    }
    
    /** Retorna a ferramenta que est� seleccionada
     * @return Ferramenta seleccionada
     */    
    public AnyTool getToolSelected ()
    {
        if (toolSelected == -1) return null;
        else return tools[toolSelected];
    }
}
